#version 450

layout (binding = 0) uniform sampler2D input_rgb;
layout (binding = 1, rgba8) uniform image2D  output_l;

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main()
{
    ivec3 gid = ivec3(gl_GlobalInvocationID);

    vec4 col = texelFetch(input_rgb, gid.xy, 0);
    float grey = dot(col.rgb, vec3(0.2126, 0.7152, 0.0722));

    imageStore(output_l, gid.xy, vec4(grey, grey, grey, 1.0));
}
